export const DEFAULT_AVATAR = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk8A8AAQsAzQ/8/GkAAAAASUVORK5CYII=";

export const TIMEPHORIA_LOGO = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIiB2aWV3Qm94PSIwIDAgMjAwIDIwMCI+PGNpcmNsZSBjeD0iMTAwIiBjeT0iMTAwIiByPSIxMDAiIGZpbGw9IiMwMDAwMDAiIC8+PHRleHQgeD0iMTAwIiB5PSIxMDgiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIyMCIgZmlsbD0iI2ZmZmZmZiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC13ZWlnaHQ9ImJvbGQiIGxldHRlci1zcGFjaW5nPSIyIj5USU1FUEhPUklBPC90ZXh0Pjwvc3ZnPg==';

export const DISCLAIMERS = [
  "HARGA BERLAKU UTK PEMBELIAN SAAT PAYDAY SALE TGL (dd-mm-yyyy) DI TIKTO LIVE TIME PHORIA & DAPAT BERUBAH SEWAKTU-WAKTU",
  
  // Teks Anda ditambahkan / direvisi di sini:
  "HAK CIPTA DARI (@KOL) TELAH RESMI DISETUJUI UNTUK DIGUNAKAN OLEH TIME PHORIA. HARGA DAPAT BERUBAH SEWAKTU WAKTU",
  "BAWA PULANG (BARANG) DARI TIMEPHORIA, BERLAKU UNTUK PEMBELOAN DI (CAMPAIGN DAN TANGGAL)).KEPUTUSAN BERADA DI TANGAN TIMEPHORIA",
  "REAKSI DARI PENGGUNAAN MAKEUP TERGANTUNG PADA JENIS KULIT, USIA, PENGGABUNGAN DENGAN PRODUK MAKEUP LAIN, DAN FAKTOR LAINNYA",
  "HARGA DAPAT BERUBAH SEWAKTU WAKTU SESUAI AKUN DAN PERIODE PROMO",
  "BEBERAPA BAGIAN DALAM VIDEO INI MENGANDUNG KONTEN YANG DIBUAT MENGGUNAKAN AI"
];

export const WA_COLORS = ['#e53935', '#d81b60', '#8e24aa', '#5e35b1', '#3949ab', '#1e88e5', '#039be5', '#00897b', '#00838f', '#2e7d32', '#43a047', '#f57c00', '#ef6c00', '#d84315'];

export const THEME_COLORS = {
  tiktokDarkBg: "#121212",
  tiktokLightBg: "#ffffff",
  tiktokGrayText: "#8a8b91",
  tiktokWhiteText: "#ffffff",
  tiktokBlackText: "#161823",
  waTerangBg: '#efeae2',
  waGelapBg: '#0b141a'
};